name: firebase_flutter_cifo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  go_router: ^17.0.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  uuid: ^4.5.2
  http: ^1.5.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.2
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
